"""empty message

Revision ID: f18ead841366
Revises: 
Create Date: 2020-08-09 22:52:33.996714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18ead841366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('CUIT', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('fecha_desde_que_es_cliente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.Enum('error', 'consulta', 'mejora'), nullable=False),
    sa.Column('estado', sa.Enum('nuevo', 'en progreso', 'esperando informacion', 'cerrado'), nullable=False),
    sa.Column('severidad', sa.Enum('baja', 'media', 'alta'), nullable=True),
    sa.Column('legajo_responsable', sa.Integer(), nullable=True),
    sa.Column('pasos', sa.String(length=300), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets_tareas',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id_ticket', 'id_tarea')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_tareas')
    op.drop_table('tickets')
    op.drop_table('clientes')
    # ### end Alembic commands ###
